//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public decimal PhoneNumber { get; set; }
        public System.DateTime DOB { get; set; }
        public bool Gender { get; set; }
        public string InstrumentChoice { get; set; }
        public decimal NationalId { get; set; }
        public string College { get; set; }
        public string Faculty { get; set; }
        public System.DateTime YearOfStudy { get; set; }
        public bool Disability { get; set; }
        public byte[] NationalIdImage { get; set; }
        public byte[] CollegeIdImage { get; set; }
        public byte[] PersonalImage { get; set; }
    }
}
